### ISSUE TITLE
drawToPIL?

### ISSUE THREAD

**Issue by niknah-netlify** [deeplook/svglib#473]
How do I use drawToPIL?  This was working in v1.6.0.  Not in v2.0.2.   Using reportlab==5.0.0.

```
from svglib.svglib import svg2rlg
from reportlab.graphics.renderPM import drawToPIL

drawing = svg2rlg("arcs01.svg")
pil = drawToPIL(drawing)
```

Error...

```
    pil = drawToPIL(drawing)
          ^^^^^^^^^^^^^^^^^^
  File "miniconda3\envs\comfyui312\Lib\site-packages\reportlab\graphics\renderPM.py", line 708, in drawToPIL
    return drawToPMCanvas(d, dpi=dpi, bg=bg, configPIL=configPIL, showBoundary=showBoundary, backend=backend,backendFmt=backendFmt, **kwds).toPIL()
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "miniconda3\envs\comfyui312\Lib\site-packages\reportlab\graphics\renderPM.py", line 702, in drawToPMCanvas
    d = renderScaledDrawing(d)
        ^^^^^^^^^^^^^^^^^^^^^^
  File "miniconda3\envs\comfyui312\Lib\site-packages\reportlab\graphics\renderbase.py", line 153, in renderScaledDrawing
    renderScale = d.renderScale
                  ^^^^^^^^^^^^^
AttributeError: 'NoneType' object has no attribute 'renderScale'
```

Thanks

**Comment by deeplook** [comment]
Thanks for the report! There are actually two things going wrong here, one masking the other.

**The immediate error**, `'NoneType' object has no attribute 'renderScale'`, means `svg2rlg()` returned `None`. That happens when `load_svg_file` fails to parse the SVG (file not found, XML error, etc.) and swallows the exception silently. Worth adding a quick sanity check:

```python
import logging
logging.basicConfig(level=logging.WARNING)

drawing = svg2rlg("arcs01.svg")
if drawing is None:
    raise ValueError("svg2rlg returned None — check the log above for the real error")
pil = drawToPIL(drawing)
```

That should surface the actual parse failure.

**The deeper issue, why it broke between 1.6.0 and 2.0.2,** is related to your Cairo question. In svglib 1.6.0, `rlpycairo` was a required dependency, so Cairo was always present. In 2.0.2 it was moved to an optional `[bitmaps]` extra. At the same time, reportlab 5.0.0 dropped the old `_renderPM` C extension entirely and now requires Cairo for all pixel rendering (`rl_settings.py` says so explicitly: `renderPMBackend='rlPyCairo' #rl_renderPM is gone`).

So on svglib 2.0.2 + reportlab 5.0.0 without `rlpycairo` installed, `drawToPIL` simply can't work at all. The fix is:

```
pip install "svglib[bitmaps]"
```

That pulls in `rlpycairo` and the Cairo system library. Once you do that, and once the `svg2rlg` parse issue is resolved, `drawToPIL` should work again.

We should probably document this in the migration notes for 2.0.x, the interaction between dropping `rlpycairo` as a hard dep and reportlab 5.0.0 requiring it isn't obvious.

**Comment by niknah** [comment]
I have.

rlPyCairo==0.4.0
reportlab==5.0.0
svglib==2.0.2

Same error with older reportlab too
reportlab==4.4.10

**Comment by deeplook** [comment]
Can you use the following `Dockerfile.issue473` with any version combinations that reproduces your error?

```Docker
# docker build -t svglib-issue473 - < Dockerfile.issue473
# docker run --rm svglib-issue473

FROM python:3.12-slim

# Cairo system library + build tools needed by pycairo (rlPyCairo dep)
RUN apt-get update && apt-get install -y --no-install-recommends \
        gcc \
        meson \
        ninja-build \
        pkg-config \
        libcairo2-dev \
        python3-dev \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

# Exact versions from the issue report
RUN pip install --no-cache-dir \
        "svglib==2.0.2" \
        "reportlab==4.4.10" \
        "rlPyCairo==0.4.0"

# Extract arcs01.svg from the svglib 2.0.2 source distribution
RUN pip download svglib==2.0.2 --no-deps --no-binary svglib -d /tmp/sdist -q \
    && tar -xzf /tmp/sdist/svglib-2.0.2.tar.gz -C /tmp/sdist svglib-2.0.2/tests/samples/misc/arcs01.svg \
    && mv /tmp/sdist/svglib-2.0.2/tests/samples/misc/arcs01.svg arcs01.svg \
    && rm -rf /tmp/sdist

# reproduce.py mirrors the exact code from issue #473
RUN cat > reproduce.py << 'EOF'
import logging
logging.basicConfig(level=logging.WARNING)

from svglib.svglib import svg2rlg
from reportlab.graphics.renderPM import drawToPIL

print("=== Step 1: reproduce the issue (missing file → svg2rlg returns None) ===")
drawing = svg2rlg("missing.svg")
if drawing is None:
    print("svg2rlg returned None (file not found) — this is the root cause")
    try:
        pil = drawToPIL(drawing)
    except AttributeError as e:
        print(f"AttributeError: {e}")
        print("^ Misleading error; real problem is svg2rlg returned None\n")

print("=== Step 2: run with the actual arcs01.svg ===")
drawing = svg2rlg("arcs01.svg")
if drawing is None:
    print("FAIL: svg2rlg returned None even for arcs01.svg")
else:
    pil = drawToPIL(drawing)
    print(f"OK: PIL image created — mode={pil.mode} size={pil.size}")
EOF

CMD ["python", "reproduce.py"]
```

**Comment by deeplook** [comment]
I could not reproduce this (see above), could you? If not, let's close this.

**Comment by niknah-netlify** [comment]
Tried it again now.  Seems to be working.  Thanks for the suggestions.
